### ISSUE TITLE
Error handling of GraphQL responses with error keys

### ISSUE THREAD

**Issue by GROwen** [salsadigitalauorg/lagoon_ansible_collection#64]
When using the gql client to [create a project](https://github.com/salsadigitalauorg/lagoon_ansible_collection/blob/feature/update-error-handling/api/plugins/action/project.py#L173) if the response from the server includes an error key the plugin fails with the following error

### Error
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/share/ansible/collections/ansible_collections/lagoon/api/plugins/module_utils/gql.py", line 68, in execute_query
    res = self.client.execute(query_ast, variable_values=variables)
  File "/usr/local/lib/python3.10/site-packages/gql/client.py", line 403, in execute
    return self.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/gql/client.py", line 221, in execute_sync
    return session.execute(
  File "/usr/local/lib/python3.10/site-packages/gql/client.py", line 860, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': "Cannot read properties of undefined (reading 'id')", 'locations': [{'line': 2, 'column': 3}], 'path': ['projectByName']}
```
The behaviour of the `TransportQueryError` is documented here - https://gql.readthedocs.io/en/stable/advanced/error_handling.html#transport-errors

> [TransportQueryError](https://gql.readthedocs.io/en/stable/modules/transport_exceptions.html#gql.transport.exceptions.TransportQueryError): There was a specific error returned from the server for your query. The message you receive in this error has been created by the backend, not gql! In that case, the connection to the server is still available and you are free to try to send other queries using the same connection. The message of the exception contains the first error returned by the backend. All the errors messages are available in the exception errors attribute.

### Steps to reproduce
This is the unabstracted request that is generated by the [has_project method](https://github.com/salsadigitalauorg/lagoon_ansible_collection/blob/feature/update-error-handling/api/plugins/action/project.py#L8) that triggers the error.
**Request**
```
curl --location 'https://api.lagoon.amazeeio.cloud/graphql' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer token
--data '{"query":"query project($name: String!) {\n    projectByName(name: $name) {\n        id\n    }\n}","variables":{"name":"vrqa-vic-gov-au"}}'
```

**Response**
```
{
    "errors": [
        {
            "message": "Cannot read properties of undefined (reading 'id')",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "projectByName"
            ]
        }
    ],
    "data": {
        "projectByName": null
    }
}
```

#### To reproduce the error programmatically 
We're using api.project plugin in an Ansible playbook in the following way
```
- name: Ensure the project exists in Lagoon
  lagoon.api.project:
    state: present
    name: "{{ project_name }}"
    git_url: "{{ config.gitUrl | default('') }}"
    development_environments_limit: "{{ config.developmentEnvironmentsLimit | default(5) }}"
    auto_idle: "{{ config.autoIdle | default(1) | int  }}"
    production_environment: "{{ config.productionEnvironment | default('production') }}"
    openshift: "{{ cluster_id | default(159) }}"
  when:
    - config_file.stat.exists
```
